In [1]:
import numpy as np
import sklearn

## 特征编码之二元化（数值型转为布尔值，连续性转为离散型）

In [2]:
from sklearn.preprocessing import Binarizer

In [3]:
x = [[1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [3, 3, 3, 3, 3,],
    [1, 1, 1, 1, 1,]]
binarizer = Binarizer(threshold=2.5)

In [4]:
binarizer.transform(x)

array([[0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

## 独热编码

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [6]:
x = [[1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [3, 3, 3, 3, 3,],
    [1, 1, 1, 1, 1,]]
encoder = OneHotEncoder(sparse=False)#是否稀疏#实例化

In [9]:
encoder.fit(x)

OneHotEncoder(sparse=False)

In [13]:
encoder.transform([[1, 2, 3, 4, 1]])

array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.]])

In [14]:
x1 = [[1, 2, 3, 4, 5],
    [2, 1, 3, 2, 1],
    [1, 1, 1, 3, 3,],
    [1, 1, 1, 1, 1,]]
encoder1 = OneHotEncoder(sparse=False)#是否稀疏#实例化对象
encoder1.fit(x)
encoder1.transform([[1, 2, 3, 4, 1]])
encoder1.active_features_#激活的特征序号
encoder1.feature_indices_#起始位置

array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.]])

In [37]:
encoder1.get_feature_names()

array(['x0_1', 'x0_3', 'x0_5', 'x1_1', 'x1_2', 'x1_3', 'x1_4', 'x2_1',
       'x2_3', 'x3_1', 'x3_2', 'x3_3', 'x3_4', 'x4_1', 'x4_3', 'x4_5'],
      dtype=object)

In [17]:
encoder1.active_features_#激活的特征序号
encoder1.feature_indices_#起始位置

AttributeError: 'OneHotEncoder' object has no attribute 'active_features_'

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

n_samples = 50
data = pd.DataFrame({'colors': np.random.choice(['red', 'blue', 'green'], n_samples),
                     'shapes': np.random.choice(['circle', 'square'], n_samples)})

y = np.random.choice(['apples', 'oranges'], n_samples)

enc = OneHotEncoder()
X = enc.fit_transform(data)
lr = LogisticRegression().fit(X, y)

pd.DataFrame({'feature_names': enc.get_feature_names(data.columns),
                      'coef': np.squeeze(lr.coef_)})

feature_names      coef
0    colors_blue  0.096088
1   colors_green -0.370143
2     colors_red  0.274070
3  shapes_circle  0.102461
4  shapes_square -0.102446

### enc.get_feature_names#Return feature names for output features.

## 数据标准化

In [21]:
data = [[0,0],[0,0],[1,1],[1,1]]

In [22]:
scaler = sklearn.preprocessing.StandardScaler().fit(data)#数据的均值与方差

In [26]:
scaler.transform([[0,0]])

array([[-1., -1.]])

## 最大最小标准化

In [33]:
scaler1 = sklearn.preprocessing.MinMaxScaler(feature_range=(0,1)).fit(data)
scaler1.transform([[3,4]])

array([[3., 4.]])

## 样本正则化

In [34]:
x = [[1, -1, 2],
    [2, 0, 0],
    [0, 1, -1]]

In [36]:
sklearn.preprocessing.normalize(x, norm='l2')

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])